---
:conf:
  telegram_token: '123456678:qwertyuiop'

  proxy: http://my.proxy.address:1234
  proxy_user: username
  proxy_pass: password
  proxy_http: no

  service_port: 8003
  service_token: 'secret'
  server_base: 'https://qqqqqqqq.ngrok.io'

  fb_token: qweqweqweqweqweqweqweqweqweqweqwe
  fb_verify_token: 123456
  fb_app_secret: qweasdzxc
  fb_port: 5550

  text_socket: /tmp/tele_text_sock
  users: ./bot_users.yaml

:states:
  main:
    unauthorized: unauth1
    :events:
      e1:
        state: e2
      e3:
        exec: true
        ok_state: e2
        fail_state: main
      e4:
        state: e4
      e5:
        state: e5
      sub:
        state: sub
      unsub:
        state: unsub
      sub_list:
        state: sub_list
      c1:
        mystr: OK
        state: check1
      c2:
        mystr: NOT OK
        state: check1
      menu_check:
        state: menu_check
    :menu:
      e1: "Hello!"
      e3: Hello2
      e4: image
      e5: "YES"
      sub: subscribe me
      unsub: unsubscribe me
      sub_list: my subscriptions
      c1: check ok
      c2: check not ok
      menu_check: submenu
    msg: Make your choice


  unauth1:
    msg: "Talk to me?"
    :events:
      auth:
        state: do_auth
      _other:
        state: unauth2

  unauth2:
    auth_check: "The best answer?"
    auth_answer: "42"
    ok_state: main
    auth_msg: Yes! Now you've got priveleges
    fail_state: unauth1
    auth_fail: Ooops, no....

  e2:
    msg: Hellllllooooooo!
    state: main

  cluster:
    exec: echo "check is %mystr%"

  e4:
    exec: echo /tmp/test.jpg
    is_jpeg: 1
    img: img1

  e5:
    exec: echo yes
    ok_state: e55
    fail_state: e56

  e55:
    msg: "YES!"
    state: main
  e56:
    msg: "O, NOOOO!"
    state: main

  sub:
    subscriptions: new
    prompt: Choose!
    cancel: Changed my mind
    cancel_state: main
    ok_state: main
    
  unsub:
    subscriptions: del
    prompt: What to drop?
    cancel: Changed my mind
    cancel_state: main
    ok_state: main

  sub_list:
    subscriptions: my
    next_state: e55

  menu_check:
    exec: "echo 'return=main;hi2=e2;image=e4'"
    is_menu: 1

:groups:
  important_notices: Notifications
  misc: Miscelaneous
  test: Just test
